discourse_ratelimit_posts:
  discourse_ratelimit_posts_enabled:
    default: false
    client: true
  discourse_ratelimit_posts_tl0_daily_limit:
    default: 3
    min: 0
    max: 1000
    client: false
  discourse_ratelimit_posts_tl1_daily_limit:
    default: 10
    min: 0
    max: 1000
    client: false
  discourse_ratelimit_posts_tl2_daily_limit:
    default: 20
    min: 0
    max: 1000
    client: false
  discourse_ratelimit_posts_tl3_daily_limit:
    default: 50
    min: 0
    max: 1000
    client: false
  discourse_ratelimit_posts_tl4_daily_limit:
    default: 0
    min: 0
    max: 1000
    client: false
  discourse_ratelimit_posts_exempt_categories:
    type: category_list
    default: ""
    client: false
